### ISSUE TITLE
Lost all groups/tabs, no backups (after update to 0.6.2?)

### ISSUE THREAD

**Issue by maddhin** [Morikko/sync-tab-groups#89]
Hi,

not sure if this is related to just updating to 0.6.2 but I lost all groups and (200+) tabs!!!

Worse: looking into the backup folder, there are only 5-min, 1h and 4h backups (see issue) but all those backups are also 'empty'...

Am I completely screwed now? 

Am on Win10 w/ latest FF58.

**Comment by Morikko** [comment]
> Worse: looking into the backup folder, there are only 5-min, 1h and 4h backups (see issue #88) but all those backups are also 'empty'...

For #88, I answered. 

For the empty backup, it is probably because you have no group any more. And the backup system overwrote the files. 

Against this, I added a manual back up button for having a back up that is not automatically overwritten. Although less up to date if you don't do it often.

I have no idea of the reason you lost them. I updated without losing anything. On top of that, I have all my back-up and filled.

Without more information, it will be hard to find the source of this problem.
Just in case: 
 - There is error messages in the web console ? (Ctrl+Shift+J)

> Am I completely screwed now?

If you have never exported groups manually and you have no filesystem/system backup, I have no solution.

**Comment by maddhin** [comment]
the web console shows the following errors (filtered by "moz-", I hope that is sufficient, I am not at all familiar with the web console)

`Error: Promised response from onMessage listener at initBrowser/Browser.addMessageHandlers@moz-extension://5f2bb1a3-86bd-469d-8429-55fc7d56ebd1/js/common/Browser.js:3:4034 went out of scope  undefined
Error: Promised response from onMessage listener at initBrowser/Browser.addMessageHandlers@moz-extension://5f2bb1a3-86bd-469d-8429-55fc7d56ebd1/js/common/Browser.js:3:4034 went out of scope  undefined
moz-extension://5f2bb1a3-86bd-469d-8429-55fc7d56ebd1/background.html: chrome tabs query did not return a result while changing window focus

  Log.js:3
`
Other than that, I am happy to find the problem. All I did is switch the PC off and on again the next morning with everything gone.

**Comment by Morikko** [comment]
> Other than that, I am happy to find the problem. 

Great!

None of the errors and from Sync Tab Groups. 

Have you uninstalled the extension ?

**Comment by maddhin** [comment]
> None of the errors and from Sync Tab Groups.
The laptop is off now, but once I have the same problem, I will post the whole console info. 

> As you have more than one computer, you can share back up between them.
I could but as both FF sessions are not synced, booth do have different groups / tabs -> would absolutely LOVE to have the two computers/groups/tabs in sync!!!

> Have you uninstalled the extension ?
No. The groups / tabs were gone once I switched on the laptop in the morning... Must be a bug. 
The only thing I can think of from my side is that FF has been closed through the "close window X" instead of the "end FF" (ctrl+shift+q) button. I might have used the X which seems to cause trouble (I think I saw some issue thread here about that). The other things is that FF updated to 0.6.2. No other changes.

**Comment by Morikko** [comment]
> I could but as both FF sessions are not synced, booth do have different groups / tabs -> would absolutely LOVE to have the two computers/groups/tabs in sync!!!

I might study this. But it is less priority than 1. Stability and 2. Hidden tabs 

> The laptop is off now, but once I have the same problem, I will post the whole console info.

Also, If you have data you don't want to share, you can send them by email (cf Firefox Add-On page).

**Comment by maddhin** [comment]
I'm happy to provide as much info as possible to find bugs but I have no programming background and would need clear instructions as to what could be useful for you. Like where logs are etc.

**Comment by Morikko** [comment]
I have tested the extension over and over and things are good in v0.6.3.
If it happens to someone, you can continue on this thread.

**Comment by zultron** [comment]
Not sure if it's a clue, but the extension lost the "Group Names Sorting" preference, too (the only one I customized).

**Comment by Morikko** [comment]
> Not sure if it's a clue, but the extension lost the "Group Names Sorting" preference, too (the only one I customized).

It might be the case all the local data were wiped off. I have no idea if it is the extension or the browser fault. 

I am actually working on a logging system to track behavior and errors. With this, you will be able to send it to me. It will improve my debugging capabilities.

**Comment by MacSass** [comment]
Hello, I just noticed I lost all my tabs too ... not sure exactly when, I suspect it was when the UI change happed - at least all backups from the last 3 days only show "empty group list" when I try to restore.
I guess my tabs are gone ... too bad ..
Habe set backup no to one only each day ...

**Comment by maddhin** [comment]
could this be related to closing Firefox via the X (close window) vs closing via "exit" (crtl+shift+Q)? 

Although annoying but I am forcing myself to end FF via exit for the last weeks due to the STG issues of loosing tabs etc. 

It would be actually great to get some kind of confirmation whether or not it is safe to close FF via X now.

**Comment by MacSass** [comment]
Has not happened to me again (and I always use the X to close FF).
I think it was related to some update of either FF 60 or an update of Sync-Tab-Group extension (when the UI update happened).
Will keep watching it - but for now seems to run stable ...

**Comment by Morikko** [comment]
Marco can you provide me the error log from the preferences ? (End of
settings section)

The back up are in the Groups section in the preferences.

I hope you will retrieve them.


Le lun. 28 mai 2018 à 15:30, Marco Leise <notifications@github.com> a
écrit :

**Comment by mleise** [comment]
Here you go: [SyncTabGroups-Log-20180529-094349.txt](https://github.com/Morikko/sync-tab-groups/files/2047201/SyncTabGroups-Log-20180529-094349.txt)

**Comment by mleise** [comment]
Simple Tab Groups was able to restore the backups for me.

**Comment by zultron** [comment]
Ok, this just happened again.  This morning my whole laptop hung.  Powered it off and back on again, and now all the tab groups are gone.  The log shows the extension was reinitialized.

Funny enough, I have the `.mozilla/firefox/default.default/browser-extension-data/sync-tab-groups@eric.masseran` directory under git version control.  The `storage.js` file was simply emptied out and replaced with data from the window that the FF session manager was able to restore.

[SyncTabGroups-Log-20180611-155856.json.txt](https://github.com/Morikko/sync-tab-groups/files/2091734/SyncTabGroups-Log-20180611-155856.json.txt)

**Comment by zultron** [comment]
Where are the automatic backups stored, and why are they deleted when the tabs themselves are?

**Comment by Morikko** [comment]
> Where are the automatic backups stored, and why are they deleted when the tabs themselves are?

They shouldn't.. 

> Funny enough, I have the .mozilla/firefox/default.default/browser-extension-data/sync-tab-groups@eric.masseran directory under git version control. The storage.js file was simply emptied out and replaced with data from the window that the FF session manager was able to restore.

Do the options have been reset back to the default ones ?

I need to improve the error logging to not be cleared each restart.  Sorry, for not being very reactive. At present, I don't have much available time.

**Comment by zultron** [comment]
It looks like the "Download Back Up" feature stores periodic backups in a place they won't be deleted when the addon data is.  That's a great safety feature that will allow me to keep using this nice extension until we eventually fix this problem.  Thank you!

**Comment by romiras** [comment]
I also lost all groups with all tabs altogether. All backups are empty. 
And I suspect this could happen due to computer power loss or if FF didn't exited properly.

**Comment by danve** [comment]
lost all tabs and groups today, any way to recover? at least a list of them, 
other wise the trust is for nothing
